# ===================================================================
# JHipster Sample Spring Cloud Config.
# ===================================================================

# Property used on app startup to check the config server status
configserver:
    name: Kelate Registry config server
    status: Connected to the Kelate Registry config server, using https://github.com/kelate/registry-config !

# Default JWT secret token (to be changed in production!)
jhipster:
    security:
        authentication:
            jwt:
                token-validity-in-seconds: 86400
                token-validity-in-seconds-for-remember-me: 2592000
                base64-secret: ZWFmN2I4OTRjN2ZlNDY1MTEwNDQ3MWRlMTBmNzI1MmQxMmUzZTYyZjM2ZTQ3YmZmYTZkZTVhMWI5ZTdiZjYyOWZkNDI5OWMzYzk4MDQ0YmIyODRmOWMzY2M3ZWMyOTQyNTkyOTQwMzRkMTBjY2Q3MWVjNTEyOTJlODE1NjY5ZmE
                
